### ISSUE TITLE
invalid docker-compose.yml

### ISSUE THREAD

**Issue by kietly** [InCadence/coalesce#73]
https://github.com/InCadence/coalesce/blob/master/src/Coalesce.Dist/coalesce-karaf-dist/docker-compose.yml
Should the last service look like this if build from source? mvn clean install -DskipTests -Pdist -Preact

karaf:
      image: incadencecorp/coalesce-karaf:0.0.33-SNAPSHOT 
      container_name: coalesce
      ports:
        - "8181:8181"
        - "8101:8101"
      restart: unless-stopped
      links:
        - db:db

**Comment by dclemenzi** [comment]
Correct. Sorry we don't use this docker compose file which is why it feel through the cracks but we do run Coalesce with Elastic both in Docker all the time. Here are the steps: 

- Run [Coalesce Docker](https://github.com/InCadence/coalesce/wiki/Docker-Image#running-image)
- Run the [Elastic Docker](https://github.com/InCadence/coalesce/blob/master/src/Coalesce.Framework.Persister.Elasticsearch/src/test/resources/docker-compose.yml)
- [Configure Blueprint
](https://github.com/InCadence/coalesce/wiki/ElasticSearch#bean)

With the changes you made to the Docker compose you can skip the first two steps and run docker-compose up. 

The blueprint configuration can be done via the manager (no need to bash into the image) by doing the following: 

- Browse to localhost:8181/manager
- Click the Derby persister
- Click edit
- Replace XML with the Elastic [bean] (https://github.com/InCadence/coalesce/wiki/ElasticSearch#bean)

If you use this compose file with the link then localhost works for the IP. However without the link you have to use the Docker IP of your local host.

If you are pulling the image from [Docker hub](https://hub.docker.com/r/incadencecorp/coalesce-karaf/tags/) we only have version 31 and 32 deployed not 33-SNAPSHOT.
